### ISSUE TITLE
Timeformat error on windows

### ISSUE THREAD

**Issue by shravanpn7** [Answers4AWS/graffiti-monkey#17]
I tried to execute the below command on windows and found that this is due to the python time formatting in windows (particularly %T)

reference: http://stackoverflow.com/questions/10807164/python-time-formatting-different-in-windows

C:\Users\sp>graffiti-monkey --region us-east-1 -c C:\Users\sp\De
sktop\test.yml

ValueError: Invalid format string
Logged from file core.py, line 85
Traceback (most recent call last):
  File "c:\Python27\lib\logging\__init__.py", line 859, in emit
    msg = self.format(record)
  File "c:\Python27\lib\logging\__init__.py", line 732, in format
    return fmt.format(record)
  File "c:\Python27\lib\logging\__init__.py", line 473, in format
    record.asctime = self.formatTime(record, self.datefmt)
  File "c:\Python27\lib\logging\__init__.py", line 431, in formatTime
    s = time.strftime(datefmt, ct)

**Comment by pas256** [comment]
How annoying. Can you submit a PR to fix this one please?

**Comment by shravanpn7** [comment]
@pas256  Sure.. will do.
